services:
  - type: web
    name: verifio
    runtime: python

    buildCommand: pip install -r requirements.txt

    startCommand: gunicorn app:app

    aptPackages:
      - tesseract-ocr
      - poppler-utils